CREATE TABLE posts_etiquetas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_post INTEGER NOT NULL,
  id_etiqueta INTEGER NOT NULL,
  FOREIGN KEY (id_etiqueta) REFERENCES etiquetas (id_etiqueta) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (id_post) REFERENCES posts (id_post) ON DELETE NO ACTION ON UPDATE NO ACTION
);